sonar.projectKey=dpaul20_gastos-en-pareja
sonar.projectName=gastos-en-pareja
sonar.organization=dpaul20
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/playwright-report/**,**/test-results/**,**/public/sw.js,**/src/types/database.ts
sonar.sourceEncoding=UTF-8
