import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import AuthWrapper from "@/app/AuthWrapper";
import { LoginButton } from "@/components/login-button";
import { DarkMode } from "@/components/dark-mode";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthWrapper>
            <div className="flex min-h-screen flex-col items-center justify-center p-4">
              <div className="w-full max-w-4xl rounded-lg bg-gray-100 p-6 shadow-lg dark:bg-zinc-800">
                <div className="mb-6 flex items-center justify-between">
                  <LoginButton />
                  <DarkMode />
                </div>
                {children}
              </div>
            </div>
          </AuthWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
